name: Build
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest','macos' ]
        node: [ 'latest' ]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Run Tests
        run: pnpm test:store
#      - name: E2E Tests
#        run: pnpm nx e2e
#        env:
#            CI: true
      - name: Build
        run: pnpm run build --configuration=production
        env:
          CI: true
