name: Publish to NPM
on:
  push:
    ### Publish on new tag release
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install PNPM Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build project
        run: pnpm build --project=ngxsmart
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v2
        with:
          strategy: all
          token: ${{ secrets.NPM_TOKEN }}
          package: dist/libs/ngxsmart/package.json
          access: public
