name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Import GPG key
        uses: scalingo/ghaction-import-gpg@v1
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Update version in source code
        run: |
          latest_tag=$(git describe --abbrev=0 --tags)
          version=${latest_tag#v}
          bash release.sh $version

      - name: Semantic release
        run: npx semantic-release

      - name: build demo
        run: pnpm run build:ng-kit-demo
